# Generated by Django 2.2.6 on 2019-10-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='PostProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Титул')),
                ('content', models.TextField(max_length=300, verbose_name='Контент')),
                ('datetoo', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('typecontent', models.ForeignKey(on_delete='PROTECT', to='main.Types', verbose_name='Тип')),
            ],
        ),
    ]
